### ISSUE TITLE
How does the cache work?

### ISSUE THREAD

**Issue by notflip** [php-tmdb/laravel#22]
Hi again! Still very happy with this amazing library. I'm wondering how the cache works? Is it explained somewhere? Thank you!

**Comment by MarkRedeman** [comment]
Hi @notflip apologies for the late response.

The logging is handled by the main [API](https://github.com/php-tmdb/api) package which uses [doctrine-cache](https://github.com/doctrine/cache). Here is an [example of caching](https://github.com/php-tmdb/api/blob/2.0/examples/caching.php).
By default it will use the filesystem for caching (and logging).

I personally don't have any experiences with `doctrine-cache`, though I suppose it could be possible to write an adapter that uses Laravel's caching instead of Doctrine's.
If anyone is interested in this I would gladly accept a pull request (or create one myself).

**Comment by wtfzdotnet** [comment]
Closing this issue seeing the age of it...
